### ISSUE TITLE
npm install failing with react-native RC releases

### ISSUE THREAD

**Issue by chandu0101** [lucasferreira/react-native-simpledialog-android#2]
`npm ERR! peerinvalid The package react-native@0.16.0-rc does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-simpledialog-android@1.0.2 wants react-native@>=0.13
`

**Comment by lucasferreira** [comment]
Hi @chandu0101, 

I didn't test in RN 0.16.0-rc only in 0.15 (or other stable versions). 

But you can download the module directly from Github and change the RN version inside package.json.
