### ISSUE TITLE
if you click outside the dialog, it will disappear 

### ISSUE THREAD

**Issue by Iliyass** [lucasferreira/react-native-simpledialog-android#3]
Hi, first of all thanks for this module
I want to implement a dialog for insuring the Geolocation is enabled, when the user clicks any of the buttons on the dialog, it will trigger the Geolocation check, if it's not enabled it will again show the dialog
again but when the user clicks outside of the dialog, it could disappear without triggering anything!

**Comment by lucasferreira** [comment]
Hi @Iliyass 

Sorry for my lateness, but I'd finally solved this problem.

If you update the _react-native-simpledialog-android_ in your project, when the user touch outside of dialog or use the android back button, the module will fire the sabe onPress event/callback of NEGATIVE_BUTTON in your dialog (if you have one).
