### ISSUE TITLE
RNPM integration 

### ISSUE THREAD

**Issue by joevo2** [lucasferreira/react-native-simpledialog-android#5]
https://github.com/rnpm/rnpm

**Comment by lucasferreira** [comment]
Hi @joevo2 

Do you know how rnpm works? Do I have to submit the package in other place than _npm registry_?

**Comment by joevo2** [comment]
Hmm not sure about the submission part you can refer to the readme at their GitHub. Maybe need to create some configuration file not very sure. But the benefit is we don't have to manually add the lines in the gradle file and the main activity it will auto add very nice and convenient 

On Wed, Mar 16, 2016 at 2:45 PM -0700, "Lucas Ferreira" notifications@github.com wrote:

Hi @joevo2 

Do you know how rnpm works? Do I have to submit the package in other place than npm registry?
